
#macro FIGGY_WINDOW_NAME "Figgy"
#macro FIGGY_WINDOW_START_VISIBLE true
#macro FIGGY_WINDOW_X 8
#macro FIGGY_WINDOW_Y 27
#macro FIGGY_WINDOW_WIDTH 400
#macro FIGGY_WINDOW_HEIGHT 600

#macro FIGFY_SLIDER_INT_STEP 1
#macro FIGFY_SLIDER_FLOAT_STEP 0.1
