
#macro FIGGY_WINDOW_NAME "Figgy"
#macro FIGGY_WINDOW_START_VISIBLE true
#macro FIGGY_WINDOW_X 8
#macro FIGGY_WINDOW_Y 27
#macro FIGGY_WINDOW_WIDTH 400
#macro FIGGY_WINDOW_HEIGHT 600

#macro FIGGY_SECTION_DEFAULT_OPEN true
#macro FIGGY_GROUP_DEFAULT_SELFSCOPE true
#macro FIGGY_GROUP_DEFAULT_ALIGN FIGGY_GROUP_ALIGN.CENTER
#macro FIGGY_UNGROUP_DEFAULT_SEPARATE true
#macro FIGGY_INT_DEFAULT_STEP 1
#macro FIGGY_FLOAT_DEFAULT_STEP 0.1
